// frontend/src/lib/components/AddFamilyModal.svelte
<script lang="ts">
  import { t } from 'svelte-i18n';
  import { familyApi } from '$lib/api/services';

  interface Props {
    show: boolean;
    onClose: () => void;
    onSuccess: () => void;
  }

  let { show = $bindable(), onClose, onSuccess }: Props = $props();

  interface Parent {
    name: string;
    phone: string;
    email: string;
    relationship_type: string;
  }

  interface Child {
    first_name: string;
    last_name: string;
    birthdate: string;
    allergies: string;
    notes: string;
  }

  let parents = $state<Parent[]>([
    { name: '', phone: '', email: '', relationship_type: 'Mom' }
  ]);

  let children = $state<Child[]>([
    { first_name: '', last_name: '', birthdate: '', allergies: '', notes: '' }
  ]);

  let submitting = $state(false);
  let error = $state<string | null>(null);

  function addParent() {
    parents = [...parents, { name: '', phone: '', email: '', relationship_type: 'Mom' }];
  }

  function removeParent(index: number) {
    if (parents.length > 1) {
      parents = parents.filter((_, i) => i !== index);
    }
  }

  function addChild() {
    children = [...children, { first_name: '', last_name: '', birthdate: '', allergies: '', notes: '' }];
  }

  function removeChild(index: number) {
    if (children.length > 1) {
      children = children.filter((_, i) => i !== index);
    }
  }

  function validateForm(): boolean {
    // Check at least one parent
    if (parents.length === 0 || !parents.some(p => p.name.trim())) {
      error = $t('checkin.atLeastOneParent');
      return false;
    }

    // Check all parents have names
    for (const parent of parents) {
      if (!parent.name.trim()) {
        error = $t('checkin.validationError');
        return false;
      }
    }

    // Check at least one child
    if (children.length === 0) {
      error = $t('checkin.atLeastOneChild');
      return false;
    }

    // Check all children have required fields
    for (const child of children) {
      if (!child.first_name.trim() || !child.last_name.trim() || !child.birthdate.trim()) {
        error = $t('checkin.validationError');
        return false;
      }
    }

    return true;
  }

  async function handleSubmit() {
    error = null;

    if (!validateForm()) {
      return;
    }

    submitting = true;

    try {
      // Prepare data for API
      const parentsData = parents.map(p => ({
        name: p.name.trim(),
        phone: p.phone.trim() || undefined,
        email: p.email.trim() || undefined,
        relationship_type: p.relationship_type
      }));

      const childrenData = children.map(c => ({
        first_name: c.first_name.trim(),
        last_name: c.last_name.trim(),
        birthdate: c.birthdate.trim(),
        allergies: c.allergies.trim() || undefined,
        notes: c.notes.trim() || undefined
      }));

      await familyApi.create({
        parents: parentsData,
        children: childrenData
      });

      // Reset form
      parents = [{ name: '', phone: '', email: '', relationship_type: 'Mom' }];
      children = [{ first_name: '', last_name: '', birthdate: '', allergies: '', notes: '' }];

      onSuccess();
      onClose();
    } catch (err) {
      console.error('Failed to create family:', err);
      error = $t('checkin.createError');
    } finally {
      submitting = false;
    }
  }

  function handleCancel() {
    // Reset form
    parents = [{ name: '', phone: '', email: '', relationship_type: 'Mom' }];
    children = [{ first_name: '', last_name: '', birthdate: '', allergies: '', notes: '' }];
    error = null;
    onClose();
  }
</script>

{#if show}
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50 overflow-y-auto">
    <div class="bg-white rounded-lg p-6 max-w-4xl w-full max-h-[90vh] overflow-y-auto">
      <h2 class="text-2xl font-bold mb-6">{$t('checkin.addFamilyTitle')}</h2>

      {#if error}
        <div class="bg-danger-50 border border-danger-200 rounded-button p-4 mb-4">
          <div class="text-danger-800 font-semibold">{error}</div>
        </div>
      {/if}

      <!-- Parents Section -->
      <div class="mb-8">
        <h3 class="text-xl font-semibold mb-4">{$t('checkin.parentInfo')}</h3>

        {#each parents as parent, index}
          <div class="border border-neutral-300 rounded-button p-4 mb-4">
            <div class="flex justify-between items-center mb-3">
              <span class="font-semibold text-neutral-700">Parent {index + 1}</span>
              {#if parents.length > 1}
                <button
                  type="button"
                  class="text-danger-600 hover:text-danger-700 text-sm"
                  onclick={() => removeParent(index)}
                >
                  {$t('checkin.removeParent')}
                </button>
              {/if}
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-semibold text-neutral-700 mb-1">
                  {$t('checkin.parentName')} <span class="text-danger-600">*</span>
                </label>
                <input
                  type="text"
                  class="w-full px-4 py-2 border border-neutral-300 rounded-input focus:outline-none focus:ring-2 focus:ring-primary-500"
                  placeholder={$t('checkin.parentNamePlaceholder')}
                  bind:value={parent.name}
                  required
                />
              </div>

              <div>
                <label class="block text-sm font-semibold text-neutral-700 mb-1">
                  {$t('checkin.relationshipType')} <span class="text-danger-600">*</span>
                </label>
                <select
                  class="w-full px-4 py-2 border border-neutral-300 rounded-input focus:outline-none focus:ring-2 focus:ring-primary-500"
                  bind:value={parent.relationship_type}
                >
                  <option value="Mom">{$t('checkin.relationshipMom')}</option>
                  <option value="Dad">{$t('checkin.relationshipDad')}</option>
                  <option value="Other">{$t('checkin.relationshipOther')}</option>
                </select>
              </div>

              <div>
                <label class="block text-sm font-semibold text-neutral-700 mb-1">
                  {$t('checkin.parentPhone')}
                </label>
                <input
                  type="tel"
                  class="w-full px-4 py-2 border border-neutral-300 rounded-input focus:outline-none focus:ring-2 focus:ring-primary-500"
                  placeholder={$t('checkin.parentPhonePlaceholder')}
                  bind:value={parent.phone}
                />
              </div>

              <div>
                <label class="block text-sm font-semibold text-neutral-700 mb-1">
                  {$t('checkin.parentEmail')}
                </label>
                <input
                  type="email"
                  class="w-full px-4 py-2 border border-neutral-300 rounded-input focus:outline-none focus:ring-2 focus:ring-primary-500"
                  placeholder={$t('checkin.parentEmailPlaceholder')}
                  bind:value={parent.email}
                />
              </div>
            </div>
          </div>
        {/each}

        <button
          type="button"
          class="bg-primary-100 hover:bg-primary-200 text-primary-700 font-semibold px-4 py-2 rounded-button"
          onclick={addParent}
        >
          + {$t('checkin.addParent')}
        </button>
      </div>

      <!-- Children Section -->
      <div class="mb-8">
        <h3 class="text-xl font-semibold mb-4">{$t('checkin.childInfo')}</h3>

        {#each children as child, index}
          <div class="border border-neutral-300 rounded-button p-4 mb-4">
            <div class="flex justify-between items-center mb-3">
              <span class="font-semibold text-neutral-700">Child {index + 1}</span>
              {#if children.length > 1}
                <button
                  type="button"
                  class="text-danger-600 hover:text-danger-700 text-sm"
                  onclick={() => removeChild(index)}
                >
                  {$t('checkin.removeChild')}
                </button>
              {/if}
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-semibold text-neutral-700 mb-1">
                  {$t('checkin.childFirstName')} <span class="text-danger-600">*</span>
                </label>
                <input
                  type="text"
                  class="w-full px-4 py-2 border border-neutral-300 rounded-input focus:outline-none focus:ring-2 focus:ring-primary-500"
                  placeholder={$t('checkin.childFirstNamePlaceholder')}
                  bind:value={child.first_name}
                  required
                />
              </div>

              <div>
                <label class="block text-sm font-semibold text-neutral-700 mb-1">
                  {$t('checkin.childLastName')} <span class="text-danger-600">*</span>
                </label>
                <input
                  type="text"
                  class="w-full px-4 py-2 border border-neutral-300 rounded-input focus:outline-none focus:ring-2 focus:ring-primary-500"
                  placeholder={$t('checkin.childLastNamePlaceholder')}
                  bind:value={child.last_name}
                  required
                />
              </div>

              <div>
                <label class="block text-sm font-semibold text-neutral-700 mb-1">
                  {$t('checkin.childBirthdate')} <span class="text-danger-600">*</span>
                </label>
                <input
                  type="date"
                  class="w-full px-4 py-2 border border-neutral-300 rounded-input focus:outline-none focus:ring-2 focus:ring-primary-500"
                  bind:value={child.birthdate}
                  required
                />
              </div>

              <div>
                <label class="block text-sm font-semibold text-neutral-700 mb-1">
                  {$t('checkin.childAllergies')}
                </label>
                <input
                  type="text"
                  class="w-full px-4 py-2 border border-neutral-300 rounded-input focus:outline-none focus:ring-2 focus:ring-primary-500"
                  placeholder={$t('checkin.childAllergiesPlaceholder')}
                  bind:value={child.allergies}
                />
              </div>

              <div class="md:col-span-2">
                <label class="block text-sm font-semibold text-neutral-700 mb-1">
                  {$t('checkin.childNotes')}
                </label>
                <textarea
                  class="w-full px-4 py-2 border border-neutral-300 rounded-input focus:outline-none focus:ring-2 focus:ring-primary-500"
                  rows="2"
                  placeholder={$t('checkin.childNotesPlaceholder')}
                  bind:value={child.notes}
                ></textarea>
              </div>
            </div>
          </div>
        {/each}

        <button
          type="button"
          class="bg-success-100 hover:bg-success-200 text-success-700 font-semibold px-4 py-2 rounded-button"
          onclick={addChild}
        >
          + {$t('checkin.addChild')}
        </button>
      </div>

      <!-- Action Buttons -->
      <div class="flex gap-3 justify-end">
        <button
          type="button"
          class="bg-neutral-200 hover:bg-neutral-300 text-neutral-800 font-semibold px-6 py-2 rounded-button"
          onclick={handleCancel}
          disabled={submitting}
        >
          {$t('common.cancel')}
        </button>
        <button
          type="button"
          class="bg-primary-600 hover:bg-primary-700 text-white font-semibold px-6 py-2 rounded-button"
          onclick={handleSubmit}
          disabled={submitting}
        >
          {submitting ? $t('checkin.creating') : $t('checkin.createFamily')}
        </button>
      </div>
    </div>
  </div>
{/if}

// src/components/check-in/add-family-modal.tsx
"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { api } from "~/trpc/react";
import { toast } from "sonner";
import { CalendarIcon, Loader2 } from "lucide-react";
import { Calendar } from "@/components/ui/calendar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { format } from "date-fns";

interface AddFamilyModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onFamilyCreated?: (familyId: string) => void;
}

interface ParentFormData {
  name: string;
  phone: string;
  email: string;
  relationshipType: string;
}

interface ChildFormData {
  firstName: string;
  lastName: string;
  birthdate: Date | undefined;
  allergies: string;
  notes: string;
}

export function AddFamilyModal({
  open,
  onOpenChange,
  onFamilyCreated,
}: AddFamilyModalProps) {
  const t = useTranslations("checkIn");
  const tCommon = useTranslations("common");

  const [parent, setParent] = useState<ParentFormData>({
    name: "",
    phone: "",
    email: "",
    relationshipType: "parent",
  });

  const [child, setChild] = useState<ChildFormData>({
    firstName: "",
    lastName: "",
    birthdate: undefined,
    allergies: "",
    notes: "",
  });

  const [errors, setErrors] = useState<Record<string, string>>({});

  const createMutation = api.family.create.useMutation({
    onSuccess: (data) => {
      toast.success(t("familyAddedSuccess"));
      onFamilyCreated?.(data.id);
      handleClose();
    },
    onError: (error) => {
      toast.error(error.message);
    },
  });

  const handleClose = () => {
    setParent({
      name: "",
      phone: "",
      email: "",
      relationshipType: "parent",
    });
    setChild({
      firstName: "",
      lastName: "",
      birthdate: undefined,
      allergies: "",
      notes: "",
    });
    setErrors({});
    onOpenChange(false);
  };

  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {};

    if (!parent.name.trim()) {
      newErrors.parentName = t("parentNameRequired");
    }
    if (!parent.phone.trim()) {
      newErrors.parentPhone = t("parentPhoneRequired");
    }
    if (parent.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(parent.email)) {
      newErrors.parentEmail = t("invalidEmail");
    }
    if (!child.firstName.trim()) {
      newErrors.childFirstName = t("childFirstNameRequired");
    }
    if (!child.lastName.trim()) {
      newErrors.childLastName = t("childLastNameRequired");
    }
    if (!child.birthdate) {
      newErrors.childBirthdate = t("childBirthdateRequired");
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async () => {
    if (!validateForm()) {
      return;
    }

    await createMutation.mutateAsync({
      parents: [
        {
          name: parent.name.trim(),
          phone: parent.phone.trim(),
          email: parent.email.trim() || undefined,
          relationshipType: parent.relationshipType,
        },
      ],
      children: [
        {
          firstName: child.firstName.trim(),
          lastName: child.lastName.trim(),
          birthdate: child.birthdate!,
          allergies: child.allergies.trim() || undefined,
          notes: child.notes.trim() || undefined,
        },
      ],
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>{t("addNewFamily")}</DialogTitle>
          <DialogDescription>{t("addFamilyDescription")}</DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {/* Parent Information */}
          <div className="space-y-4">
            <h3 className="font-semibold">{t("parentInformation")}</h3>

            <div className="space-y-2">
              <Label htmlFor="parent-name">
                {t("parentName")} <span className="text-destructive">*</span>
              </Label>
              <Input
                id="parent-name"
                value={parent.name}
                onChange={(e) =>
                  setParent({ ...parent, name: e.target.value })
                }
                placeholder={t("parentNamePlaceholder")}
              />
              {errors.parentName && (
                <p className="text-sm text-destructive">{errors.parentName}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="parent-phone">
                {t("parentPhone")} <span className="text-destructive">*</span>
              </Label>
              <Input
                id="parent-phone"
                type="tel"
                value={parent.phone}
                onChange={(e) =>
                  setParent({ ...parent, phone: e.target.value })
                }
                placeholder={t("parentPhonePlaceholder")}
              />
              {errors.parentPhone && (
                <p className="text-sm text-destructive">{errors.parentPhone}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="parent-email">{t("parentEmail")}</Label>
              <Input
                id="parent-email"
                type="email"
                value={parent.email}
                onChange={(e) =>
                  setParent({ ...parent, email: e.target.value })
                }
                placeholder={t("parentEmailPlaceholder")}
              />
              {errors.parentEmail && (
                <p className="text-sm text-destructive">{errors.parentEmail}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="relationship-type">
                {t("relationshipType")} <span className="text-destructive">*</span>
              </Label>
              <Select
                value={parent.relationshipType}
                onValueChange={(value) =>
                  setParent({ ...parent, relationshipType: value })
                }
              >
                <SelectTrigger id="relationship-type">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="parent">{t("parent")}</SelectItem>
                  <SelectItem value="guardian">{t("guardian")}</SelectItem>
                  <SelectItem value="other">{t("other")}</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Child Information */}
          <div className="space-y-4">
            <h3 className="font-semibold">{t("childInformation")}</h3>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="child-first-name">
                  {t("childFirstName")} <span className="text-destructive">*</span>
                </Label>
                <Input
                  id="child-first-name"
                  value={child.firstName}
                  onChange={(e) =>
                    setChild({ ...child, firstName: e.target.value })
                  }
                  placeholder={t("childFirstNamePlaceholder")}
                />
                {errors.childFirstName && (
                  <p className="text-sm text-destructive">
                    {errors.childFirstName}
                  </p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="child-last-name">
                  {t("childLastName")} <span className="text-destructive">*</span>
                </Label>
                <Input
                  id="child-last-name"
                  value={child.lastName}
                  onChange={(e) =>
                    setChild({ ...child, lastName: e.target.value })
                  }
                  placeholder={t("childLastNamePlaceholder")}
                />
                {errors.childLastName && (
                  <p className="text-sm text-destructive">
                    {errors.childLastName}
                  </p>
                )}
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="child-birthdate">
                {t("childBirthdate")} <span className="text-destructive">*</span>
              </Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    id="child-birthdate"
                    variant="outline"
                    className="w-full justify-start text-left font-normal"
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {child.birthdate ? (
                      format(child.birthdate, "PPP")
                    ) : (
                      <span className="text-muted-foreground">
                        {t("pickDate")}
                      </span>
                    )}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={child.birthdate}
                    onSelect={(date) => setChild({ ...child, birthdate: date })}
                    disabled={(date) =>
                      date > new Date() || date < new Date("1900-01-01")
                    }
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
              {errors.childBirthdate && (
                <p className="text-sm text-destructive">
                  {errors.childBirthdate}
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="child-allergies">{t("childAllergies")}</Label>
              <Textarea
                id="child-allergies"
                value={child.allergies}
                onChange={(e) =>
                  setChild({ ...child, allergies: e.target.value })
                }
                placeholder={t("childAllergiesPlaceholder")}
                rows={2}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="child-notes">{t("childNotes")}</Label>
              <Textarea
                id="child-notes"
                value={child.notes}
                onChange={(e) => setChild({ ...child, notes: e.target.value })}
                placeholder={t("childNotesPlaceholder")}
                rows={2}
              />
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleClose}>
            {tCommon("cancel")}
          </Button>
          <Button
            onClick={handleSubmit}
            disabled={createMutation.isPending}
          >
            {createMutation.isPending ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                {tCommon("loading")}
              </>
            ) : (
              t("addFamily")
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
