// frontend/src/routes/login/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { t } from 'svelte-i18n';
  import { apiClient } from '$lib/api/client';

  let errorMessage = $state('');
  let isLoading = $state(false);

  async function handleSubmit(event: Event) {
    event.preventDefault();
    const form = event.target as HTMLFormElement;
    const formData = new FormData(form);
    const username = formData.get('username') as string;
    const password = formData.get('password') as string;

    if (!username || !password) {
      errorMessage = 'Username and password are required';
      return;
    }

    isLoading = true;
    errorMessage = '';

    try {
      // Login using API client
      await apiClient.post('/auth/login/', { username, password });

      // On success, redirect to check-in page
      window.location.href = '/checkin';
    } catch (error: any) {
      isLoading = false;
      if (error.details?.error) {
        errorMessage = error.details.error;
      } else if (error.message) {
        errorMessage = error.message;
      } else {
        errorMessage = 'Login failed. Please try again.';
      }
    }
  }
</script>

<svelte:head>
  <title>{$t('login.pageTitle')}</title>
</svelte:head>

<div class="fixed inset-0 flex items-center justify-center bg-neutral-100">
  <div class="bg-white p-8 rounded-card shadow-elevation-3 w-full max-w-md z-10">
    <h1 class="text-h1 mb-6 text-center">{$t('login.title')}</h1>

    {#if errorMessage}
      <div class="bg-danger-50 border border-danger-200 text-danger-800 px-4 py-3 rounded-card mb-4">
        {errorMessage}
      </div>
    {/if}

    <form onsubmit={handleSubmit}>
      <div class="mb-4">
        <label for="username" class="block text-neutral-700 text-sm font-bold mb-2">
          {$t('login.username')}
        </label>
        <input
          type="text"
          id="username"
          name="username"
          required
          class="shadow-sm appearance-none border border-neutral-300 rounded-input w-full py-2 px-3 text-neutral-700 leading-tight focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-600"
          placeholder={$t('login.usernamePlaceholder')}
        />
      </div>

      <div class="mb-6">
        <label for="password" class="block text-neutral-700 text-sm font-bold mb-2">
          {$t('login.password')}
        </label>
        <input
          type="password"
          id="password"
          name="password"
          required
          class="shadow-sm appearance-none border border-neutral-300 rounded-input w-full py-2 px-3 text-neutral-700 leading-tight focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-600"
          placeholder={$t('login.passwordPlaceholder')}
        />
      </div>

      <div class="flex items-center justify-between">
        <button
          type="submit"
          disabled={isLoading}
          class="bg-primary-600 hover:bg-primary-700 text-white font-bold py-2 px-4 rounded-button focus:outline-none focus:ring-2 focus:ring-primary-500 w-full disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isLoading ? $t('login.loggingIn') : $t('login.submit')}
        </button>
      </div>
    </form>
  </div>
</div>

// src/app/login/page.tsx
"use client";

import * as React from "react";
import { signIn } from "next-auth/react";
import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ThemeToggle } from "~/components/theme-toggle";

export default function LoginPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const callbackUrl = searchParams.get("callbackUrl") ?? "/";

  const [username, setUsername] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [error, setError] = React.useState("");
  const [isLoading, setIsLoading] = React.useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setIsLoading(true);

    try {
      const result = await signIn("credentials", {
        username,
        password,
        redirect: false,
      });

      if (result?.error) {
        setError("Invalid username or password");
      } else if (result?.ok) {
        router.push(callbackUrl);
        router.refresh();
      }
    } catch (error) {
      setError("An error occurred. Please try again.");
      console.error("Login error:", error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-background p-4">
      <div className="absolute right-4 top-4">
        <ThemeToggle />
      </div>

      <Card className="w-full max-w-md">
        <CardHeader className="space-y-1">
          <CardTitle className="text-2xl font-bold">
            Conference Child Management
          </CardTitle>
          <CardDescription>
            Enter your credentials to access the system
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="username">Username</Label>
              <Input
                id="username"
                type="text"
                placeholder="Enter your username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                disabled={isLoading}
                required
                autoComplete="username"
                autoFocus
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                placeholder="Enter your password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                disabled={isLoading}
                required
                autoComplete="current-password"
              />
            </div>
            {error && (
              <div className="rounded-md bg-destructive/15 p-3 text-sm text-destructive">
                {error}
              </div>
            )}
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? "Signing in..." : "Sign In"}
            </Button>
          </form>
        </CardContent>
      </Card>

      <p className="mt-4 text-center text-sm text-muted-foreground">
        Conference Child Management System v1.0
      </p>
    </div>
  );
}
