// frontend/src/lib/components/ui/FeatureCard.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    title: string;
    /** Icon-tile tone: blue (primary) or green (accent). */
    tone?: 'blue' | 'green';
    /** Optional icon snippet (stroke-only SVG, currentColor). */
    icon?: Snippet;
    class?: string;
    /** Body text. */
    children: Snippet;
  }

  let { title, tone = 'blue', icon, class: className = '', children }: Props = $props();
</script>

<div class="feature-card {className}" data-tone={tone}>
  {#if icon}
    <div class="icon-tile">{@render icon()}</div>
  {/if}
  <h3 class="title">{title}</h3>
  <p class="body">{@render children()}</p>
</div>

<style>
  .feature-card {
    background: var(--surface);
    border: 1px solid var(--ink-line);
    border-radius: var(--radius-lg);
    padding: 28px 28px 24px;
    transition:
      box-shadow 0.2s ease,
      transform 0.2s ease;
  }
  .feature-card:hover {
    box-shadow: var(--shadow-sm);
    transform: translateY(-2px);
  }
  .icon-tile {
    width: 44px;
    height: 44px;
    border-radius: 11px;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 18px;
    background: var(--brand-primary-tint);
    color: var(--brand-primary);
  }
  .feature-card[data-tone='green'] .icon-tile {
    background: var(--brand-accent-tint);
    color: var(--brand-accent);
  }
  .title {
    font-size: 1rem;
    font-weight: 700;
    letter-spacing: -0.01em;
    margin: 0 0 7px;
  }
  .body {
    font-size: 0.875rem;
    color: var(--ink-soft);
    line-height: 1.55;
    margin: 0;
  }
</style>

// docs/design-system/ui-kit-reference/FeatureCard.jsx
// FeatureCard.jsx — icon-tile, h3, body. Hover lifts 2px with soft shadow.

function FeatureCard({ icon, title, children, tone = 'blue' }) {
  const [hovered, setHovered] = React.useState(false);
  const tintBg = tone === 'green' ? 'var(--brand-accent-tint)' : 'var(--brand-primary-tint)';
  const iconColor = tone === 'green' ? 'var(--brand-accent)' : 'var(--brand-primary)';
  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        background: 'var(--surface)',
        border: '1px solid var(--ink-line)',
        borderRadius: 'var(--radius-lg)',
        padding: '28px 28px 24px',
        transition: 'box-shadow 0.2s ease, transform 0.2s ease',
        boxShadow: hovered ? 'var(--shadow-sm)' : 'none',
        transform: hovered ? 'translateY(-2px)' : 'none',
      }}
    >
      <div style={{
        width: 44, height: 44, borderRadius: 11,
        background: tintBg, color: iconColor,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        marginBottom: 18,
      }}>
        {icon}
      </div>
      <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: 7, letterSpacing: '-0.01em' }}>{title}</h3>
      <p style={{ fontSize: '0.875rem', color: 'var(--ink-soft)', lineHeight: 1.55 }}>{children}</p>
    </div>
  );
}

window.FeatureCard = FeatureCard;
